######################################################################
# Automatically generated by qmake (3.0) ?? 11? 26 14:06:36 2017
######################################################################

TEMPLATE = app
TARGET = QString-thousands-separator
INCLUDEPATH += .

# Input
SOURCES += main.cpp
